### ISSUE TITLE
Bug: flipped-cards-disappearing

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/vf-compete-and-collect-tcg#3]
#### Desired Behavior

> ##### The app should ...
The app should allow users to only have to click ONCE to flip a card from their deck. 

#### Actual Behavior

> ##### The app does this instead ...
When player1 flips a card at the same time as player2. One of the player's cards will disappear. That player then has to click on their deck a second time in order to re-place the card.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...
Have two devices, signed in on separate accounts. Enter a match versus each other. Click the flip-card button at the same time on both devices.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] destructure `gameId` and `client` from `req.params`
- [x] you will `db.query` for the game `state` of that `gameId`
- [x] then, 
- [x] update `state` property `clientFaceUp` by splicing the first card from `clientDeck`
- [x] `emit` `'card-flip` event to `roomId` from `io`
- [x] respond to the client
- [x] make a new `db.query` that inserts the new `state` into the db
- [x] destructure `roomId` from `state`
- [x] const players = getUsernames(roomId)
- [x] destructure `player1` and `player2` from `players`
- [x] run logic
- [x] only if `player1FaceUp` and `player2FaceUp` are not `null`,
- [x] `emit` to `roomId` `'update-state'`, passing 'updatedState' to the client

### ⚡ Client Tasks

- [x] Update component to ...
- [x] update `flipCard()` method
- [x] it should only tell the server that the client is requesting to flip a card
- [x] keep it as a `patch` request
- [x] send `gameId` and `client` `opponent` as `params`

### 🧑‍⚕️ Clean Up Tasks
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
