### ISSUE TITLE
Bug: displaying-not-found-page

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/vf-compete-and-collect-tcg#5]
#### Desired Behavior

> ##### The app should ...

The app should allow users to access the following paths: sign-in, sign-up, home page, and the match that they are currently in. It should show the not-found page whenever the user attempts to access a path that is not one of the above.

#### Actual Behavior

> ##### The app does this instead ...

The app allows users to access paths of any match (active or inactive) from their current session. If user logs out of account1 and into account2, user can still access path's from account1's session. 

#### Steps to Reproduce

> ##### To trigger the bug, you must ...
Log into account1, start a match. Sign out of account1. Sign in to account2. Enter a path of a match that account1 was in.

## ✅ Task List
> ##### Commit checklist for tasks needed to fix the bug.

### ☁️ Server Tasks
- [ ] Update server/index.js to ...
- [ ] create get route `api/auth/:opponent`
- [ ] destructure `route` from `params
- [ ] make a db que

### ⚡ Client Tasks
- [ ] Update component to ...
- [ ] if path contains a '-'
- [ ] render the Game Component
- [ ] In Game Component
- [ ] in componentDidMount()
- [ ] call fetch with retry, pass `path` and `maxRetries` as arguments
- [ ] define fetchWithRetry(path, maxRetries) method
- [ ] init `retryCount` to 0
- [ ] make the fetch
- [ ] if it fails `increment `retryCount` by 1
- [ ] if `retryCount` is less than `maxRetries`, call fetchData
- [ ] else, console.error(err)

### 🧑‍⚕️ Clean Up Tasks
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
